# Generated by Django 4.1.5 on 2023-01-07 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('plataforma', models.CharField(max_length=10)),
                ('taxa_cobrada', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Anúncios',
            },
        ),
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('imovel_codigo', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$')])),
                ('limite_hospedes', models.CharField(max_length=1)),
                ('banheiros_quant', models.CharField(max_length=1)),
                ('permite_animais', models.BooleanField(default=False)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(10)])),
                ('data_ativa', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em:')),
                ('reserva_codigo', models.UUIDField(default=uuid.uuid1, editable='False', primary_key='True', serialize=False, unique=True)),
                ('chekin_data', models.DateField()),
                ('chekout_data', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('quant_hospedes', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('comentarios', models.TextField(blank=True, max_length=120)),
                ('reserva_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.anuncios')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AddField(
            model_name='anuncios',
            name='anuncio_imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imoveis'),
        ),
    ]
